version: "3"

services:
  postgres:
    image: postgres
    container_name: 'postgres'
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: test

volumes:
  pgdata:
