name: Go

on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # step 1: set up go
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17

      # step 2: checkout repository code
      - name: Checkout code into workspace directory
        uses: actions/checkout@v2
      - name: Install additional apps
        run: |
          sudo apt-get -y update
          sudo apt-get -y install gcc
          sudo apt-get -y install make
      # step 3: install dependencies
      - name: Install all Go dependencies
        working-directory: ./
        run: go mod vendor

      # step 5: build
      - name: build
        working-directory: ./
        run: |
          go build -o main